services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_todo
    restart: always
    working_dir: /var/www
    volumes:
      - ./laravel-app:/var/www
    networks:
      - laravel
    depends_on:
      - redis
      - database

  webserver:
    image: nginx:alpine
    container_name: nginx_todo_server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: composer_todo
    working_dir: /var/www
    volumes:
      - ./laravel-app:/var/www
    entrypoint: ["composer"]
    networks:
      - laravel

  database:
    image: mysql:8.0
    container_name: mysql_db_todo
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"   
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_todo
    ports:
      - "6379:6379"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_todo
    restart: always
    ports:
      - "8080:80"  
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - database
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
